### ISSUE TITLE
ReSpec throws errors

### ISSUE THREAD

**Issue by saschanaz** [WICG/media-playback-quality#10]
Looks like there are no `<dfn>` for the problematic types. (Are we waiting for [self-defining IDL](https://github.com/w3c/respec/issues/2316) from ReSpec?)

**Comment by marcoscaceres** [comment]
Fwiw, no. Where appropriate (attributes and operations), things should be defined.

**Comment by marcoscaceres** [comment]
Closing, as this is no longer relevant.

**Comment by saschanaz** [comment]
Yay, self-definition is here!

**Comment by marcoscaceres** [comment]
Related, thanks to @saschanaz  https://github.com/WICG/media-playback-quality/issues/14 :D
