### ISSUE TITLE
Intent to Migrate: Media Playback Quality

### ISSUE THREAD

**Issue by tidoust** [WICG/media-playback-quality#11]
## Intent to Migrate: Media Playback Quality

Hi all, cc @mounirlamouri @jernoble as chairs of the Media Working Group. The recently created [Media Working Group](https://www.w3.org/media-wg/) is ready to adopt Media Capabilities as a W3C Recommendation track deliverable.

Note some of the sections below need some love. I let people involved in the development of this proposal chime in as needed!

### Working group decision to adopt

See the [charter of the Media Working Group](https://www.w3.org/2019/05/media-wg-charter.html#deliverables)

### Proposal

Latest [Media Playback Quality draft](https://wicg.github.io/media-playback-quality/) ([Git repo](http://github.com/WICG/media-playback-quality))

### Summary

An API that extends the HTMLVideoElement to add new features that can be used to detect the user perceived playback quality. 

### Motivation and Use Cases

The API was originally part of the Media Source Extensions specification. See some motivation in the [discussion to move it to a separate extension spec](https://github.com/w3c/media-source/issues/69).

### Compatibility Risk

> Please characterize how much we might regret standardizing this new feature were we to change or remove it in the future. If you don’t have a github repository, include in this email links to relevant discussions, or documentation about support for the feature on the Web.

### Ongoing technical constraints

> What technical constraints will be added to user agents implementing this feature?

It is expected that the feature will be supported in all environments with some level of media playback (desktop, mobile, tablets, TV, etc.).

### Link to implementation experience and demos

> If your proposal has implementation experience or demos, please provide links, including common patterns in deployed libraries. Otherwise, indicate if there are none.

### Data

No quantified data but, as described in the [discussion to move it to a separate extension spec](https://github.com/w3c/media-source/issues/69), several video player libraries reported success using this interface on user agents where it is available.

### Security and Privacy

To be investigated.

### Accessibility

The proposal should not have accessibility implications.

### Internationalization

The proposal should not have internationalization implications.

**Comment by marcoscaceres** [comment]
I wonder if the media quality stats should be available for videos played from the result of user activation? Not sure how reliable it would be as finger printing mechanism, but assuming you could play back a video, and the quality results always come back consistent (always drops x frames), it could be used as a fingerprinting surface.

**Comment by marcoscaceres** [comment]
As WICG chair, this intent to migrate seems ok, though we should give people until the 17th of July to provide any additional feedback.

**Comment by marcoscaceres** [comment]
In https://github.com/whatwg/html/pull/4760, it was pointed out that this might be developed at the WHATWG (as part of HTML) instead... that would make sense, at this affects a HTML Element. 

Would it be prudent to migrate to WHATWG instead of W3C?

**Comment by domenic** [comment]
This spec seems to extend the HTML `<video>` element. As such, graduation from incubation shouldn't mean migration into a separate working group, with a standalone spec. Instead, it should be merged into the HTML Standard, as that's where the canonical definition of the `<video>` element lies.

In particular, the spec seems to make several [monkeypatches](https://annevankesteren.nl/2014/02/monkey-patch) to algorithms which are part of HTML, e.g. incrementing or resetting counters as part of the media element load algorithm, or video decoding and predecoding. Those should be expressed as pull requests to HTML modifying the appropriate algorithms, and not as monkey-patch bulleted lists in a "Concepts" section.

In general, the specification would benefit greatly from editorial review and integration into the HTML Standard.

**Comment by marcoscaceres** [comment]
I agree with @domenic. This one should go to WHATWG, where it can get good support for integrating with HTML.

**Comment by mounirlamouri** [comment]
I think we should work on this in the Media WG and then depending on the final shape of the specification decide whether it should be merged back into HTML or kept as its own spec. The current spec language is a cut and paste from MSE as there was concerns about it when it went to REC. It isn't final. We may be able to write this specification in a way that doesn't monkey patch HTMLMediaElement but if we cannot, we could either add the hooks into HTML or merge the feature there.

FWIW, MSE and Remote Playback API are specifications that extend the HTMLMediaElement but were never merged int the HTML specification.

**Comment by domenic** [comment]
> I think we should work on this in the Media WG

Why is the Media WG better than the WICG for the sort of incubation-type work you describe?

> FWIW, MSE and Remote Playback API are specifications that extend the HTMLMediaElement but were never merged int the HTML specification.

That's not great... We should fix that.

**Comment by padenot** [comment]
I agree with @mounirlamouri (https://github.com/WICG/media-playback-quality/issues/11#issuecomment-510153336), that this needs to be discussed in the Media WG (now that we have all the relevant people there), and then we can make an informed decision.

**Comment by domenic** [comment]
Can you (or @mounirlamouri) respond to my question as to why the Media WG is better than the WICG fo the sort of incubation-type work you describe? I imagine all the people in the Media WG would still be able to comment on a GitHub repo that lives under WICG/.

**Comment by padenot** [comment]
There are multiple things here.

This has been shipped by multiple implementation, so it's not quite "incubation work". However the spec itself can/will be modified to stop monkey-patching (if possible). This can technically be done anywhere as you note.

However there was a feeling, when talking with people who would comment on this type of specs, that specs were scattered too much around (sometimes even in personal repos), and that it was hard for implementors to follow all the discussions, hence why there is a move of a bunch of spec related to media things to a central location, so that they can be discussed.

I don't feel strongly either way, as long as work is being done, and `HTMLMediaElement` has less monkey-patching at the end, but for this we need everybody involved to engage with spec authors, and this is the problem it seems.

**Comment by domenic** [comment]
I share that feeling :). That's why I think it'd be great to get these modifications to `HTMLMediaElement` done in the spec that defines `HTMLMediaElement`, in collaboration with the editors of the spec that defines `HTMLMediaElement`.

**Comment by mounirlamouri** [comment]
+1 with what @padenot said.

In addition to that, I'm not a fan of having uber-gigantic specs (the idea of MSE and Remote Playback being merged into HTML is horrifying to me). I would rather have us work on making this spec standalone. After a quick read, I actually only see one HTML monkey patching: the spec multiple times mention running something when the load algorithm is invoked. This could be fixed by adding a hook in HTML. @domenic are there other issues you see here?

**Comment by domenic** [comment]
To be clear, I think standalone specs, with callouts from HTML, make a lot of sense in general. That's what I suggested for picture in picture: https://github.com/WICG/picture-in-picture/issues/150#issuecomment-509900648.

This particular spec seems intimately entwined with things defined in HTML:

- The media load algorithm
- The decoding process (including dropping frames, displaying frames, and corrupted frames)

Those all need to be integrated into the corresponding definitions in HTML. Which essentially would leave the getVideoPlaybackQuality() definition as the only remaining spec text. And for something that short, folks should not be forced to go look at a separate specification.

See also [nascent TAG guidance](https://github.com/w3ctag/design-principles/issues/99#issuecomment-494434323) on this sort of definition.

**Comment by mounirlamouri** [comment]
AFAIK, the HTML specification doesn't describe anything related to frame decoding, it stays at a "media level" which is more about the file. All the frame decoding in this spec is completely under-specified and this is why this was cut from the MSE spec to its own spec as implementations didn't match. The first thing we need to resolve here is how to describe this in a way that can guarantee interop. The Media WG is best suited to resolve this. I suggest that we discuss whether whatever solution we come up with should be merged back to HTML afterwards.

**Comment by marcoscaceres** [comment]
Ok, seems like working on this in the Media WG is where the community would like to do it. Pleading the same case as in PiP... integration back in HTML seems crucial (I'll file a bug and  point to @domenic's comments).  

@tidoust, at your convenience, please feel free to move the repository and reminder to update the metadata.

**Comment by tidoust** [comment]
Thanks @marcoscaceres, the repo has now been transferred to the W3C organization and relevant info has been updated. Closing this issue accordingly (noting #13 for discussion on integration with HTML).
